apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus-hello-world
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-hello-world
subjects:
- kind: ServiceAccount
  name: prometheus-hello-world
  namespace: monitoring-demo

